AWSTemplateFormatVersion: "2010-09-09"
Description: "Region"

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
    Description: Tipo di istanza EC2

Resources:
  RegionVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: "RegionVPC"

  RegionSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RegionVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: "RegionSubnet"

  RegionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      VpcId: !Ref RegionVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  RegionS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "region-compose-bucket-${AWS::AccountId}-${AWS::Region}"

  RegionHub:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref RegionSubnet
      SecurityGroupIds:
        - !Ref RegionSecurityGroup
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 (us-east-1)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Avvio bootstrap"
          yum update -y
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user

          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

          mkdir -p /home/ec2-user/app
          
          # Scarica il docker-compose.yml dal bucket S3
          aws s3 cp s3://${RegionS3Bucket}/docker-compose.yml /home/ec2-user/app/docker-compose.yml
          
          cd /home/ec2-user/app && docker-compose up -d
          echo "Docker e Compose installati"
