AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 con Docker e Docker Compose per simulazione servizi edge, con record A in Route53

Parameters:
  InstanceType:
    Type: String
    Default: t3.small
    Description: Tipo di istanza EC2
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-0c02fb55956c7d316
    Description: AMI da usare (Amazon Linux 2)
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: ID della subnet dove avviare l'istanza
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ID del Security Group da associare
  HostedZoneId:
    Type: String
    Description: ID della Private Hosted Zone Route53 (es. sensor-continuum.local)
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nome della chiave SSH
  ServicesInstanceName:
    Type: String
    Default: mqtt-broker-ec2
    Description: Nome dell'istanza dei servizi (EC2)
  ServicesInstanceHostname:
    Type: String
    Default: mqtt-broker.${REGION}.sensor-continuum.local
    Description: Hostname dell'istanza EC2 (deve essere un record A nella Hosted Zone)
  S3Bucket:
    Type: String
    Default: sensor-continuum-scripts
    Description: Nome del bucket S3 dove risiede lo script di inizializzazione
  InitScripts:
    Type: String
    Default: docker-install.sh
    Description: Lista di script di init separati da spazio
  DeployScripts:
    Type: String
    Default: deploy_proximity_services.sh
    Description: Lista di script di deploy separati da spazio
  EnvironmentFile:
    Type: String
    Description: File di ambiente per docker-compose

Resources:

  ServicesInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - LabRole   # nome del ruolo, non l'ARN completo

  ServicesInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref ServicesInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Ref ServicesInstanceName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          LOG_FILE="/var/log/user-data.log"
          exec > >(tee -a $LOG_FILE) 2>&1
          echo "UserData iniziato $(date)"

          # Verifica AWS CLI
          if ! command -v aws &> /dev/null; then
              echo "Installazione AWS CLI v2..."
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
              unzip /tmp/awscliv2.zip -d /tmp
              /tmp/aws/install
          fi

          # Esecuzione script di init da S3
          echo "Scarico ed eseguo script da s3://${S3Bucket}/init/"
          for script in ${InitScripts}; do
              echo "Scarico $script..."
              aws s3 cp "s3://${S3Bucket}/init/$script" "/tmp/$script"
              chmod +x "/tmp/$script"
              echo "Eseguo $script..."
              /tmp/$script
          done
          
          cd /home/ec2-user || exit 1
          
          # Scarico file di ambiente da S3
          echo "Scarico file di ambiente da s3://${S3Bucket}/compose/envs/"
          aws s3 cp "s3://${S3Bucket}/compose/envs/${EnvironmentFile}" "/home/ec2-user/.env"
          
          # Esecuzione script di deploy da S3
          echo "Scarico ed eseguo script da s3://${S3Bucket}/deploy/"
          for script in ${DeployScripts}; do
              echo "Scarico $script..."
              aws s3 cp "s3://${S3Bucket}/deploy/$script" "/home/ec2-user/$script"
              chmod +x "/home/ec2-user/$script"
              echo "Eseguo $script..."
              /home/ec2-user/$script
          done

          echo "UserData completato $(date)"

  # Record A Route53 per EC2
  ServicesInstanceRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ServicesInstanceHostname
      Type: A
      TTL: 60
      ResourceRecords:
        - !GetAtt ServicesInstance.PrivateIp

Outputs:
  InstanceId:
    Description: ID della istanza EC2
    Value: !Ref ServicesInstance
  InstanceKeyName:
    Description: Nome della chiave SSH per l'istanza
    Value: !Ref KeyName
  InstancePublicIp:
    Description: Indirizzo IP pubblico dell'istanza
    Value: !GetAtt ServicesInstance.PublicIp
  InstancePrivateIp:
    Description: Indirizzo IP privato dell'istanza
    Value: !GetAtt ServicesInstance.PrivateIp
  RecordA:
    Description: Record A creato nella Hosted Zone
    Value: !Ref ServicesInstanceRecord