AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 con Docker e Docker Compose per simulazione servizi edge

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Tipo di istanza EC2
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-0c02fb55956c7d316
    Description: AMI da usare (Amazon Linux 2)
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: ID della subnet dove avviare l'istanza
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ID del Security Group da associare
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nome della chiave SSH
  EdgeHubName:
    Type: String
    Default: edge-hub-ec2
    Description: Nome dell'istanza edge-hub
  S3Bucket:
    Type: String
    Default: sensor-continuum-scripts
    Description: Nome del bucket S3 dove risiede lo script di inizializzazione
  InitScripts:
    Type: String
    Default: docker-install.sh
    Description: Lista di script di init separati da spazio
  DeployScripts:
    Type: String
    Default: deploy_edge_services.sh
    Description: Lista di script di deploy separati da spazio

Resources:

  EdgeHubInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - LabRole   # nome del ruolo, non l'ARN completo

  EdgeHubInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref EdgeHubInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Ref EdgeHubName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          LOG_FILE="/var/log/user-data.log"
          exec > >(tee -a $LOG_FILE) 2>&1
          echo "UserData iniziato $(date)"

          # Verifica AWS CLI
          if ! command -v aws &> /dev/null; then
              echo "Installazione AWS CLI v2..."
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
              unzip /tmp/awscliv2.zip -d /tmp
              /tmp/aws/install
          fi

          # Esecuzione script di init da S3
          echo "Scarico ed eseguo script da s3://${S3Bucket}/init/"
          for script in ${InitScripts}; do
              echo "Scarico $script..."
              aws s3 cp "s3://${S3Bucket}/init/$script" "/tmp/$script"
              chmod +x "/tmp/$script"
              echo "Eseguo $script..."
              /tmp/$script
          done
          
          # Esecuzione script di deploy da S3
          echo "Scarico ed eseguo script da s3://${S3Bucket}/deploy/"
          for script in ${DeployScripts}; do
              echo "Scarico $script..."
              aws s3 cp "s3://${S3Bucket}/deploy/$script" "/tmp/$script"
              chmod +x "/tmp/$script"
              echo "Eseguo $script..."
              /tmp/$script
          done

          echo "UserData completato $(date)

Outputs:
  InstanceId:
    Description: ID della istanza EC2
    Value: !Ref EdgeHubInstance
  InstanceKeyName:
    Description: Nome della chiave SSH per l'istanza
    Value: !Ref KeyName
  InstancePublicIp:
    Description: Indirizzo IP pubblico dell'istanza
    Value: !GetAtt EdgeHubInstance.PublicIp
  InstancePrivateIp:
    Description: Indirizzo IP privato dell'istanza
    Value: !GetAtt EdgeHubInstance.PrivateIp