# --- environment base per tutti i zone hub ---
x-zone-hub-env: &zone-hub-env
  EDGE_MACROZONE: "${EDGE_MACROZONE}"
  EDGE_ZONE: "${EDGE_ZONE}"
  MQTT_BROKER_ADDRESS: "${EDGE_ZONE}.${EDGE_MACROZONE}.mqtt-broker.${REGION}.sensor-continuum.local"
  REDIS_ADDRESS: "zone-hub-${EDGE_ZONE}-cache"
  OPERATION_MODE: "loop"
  HEALTHZ_SERVER: "true"
  HEALTHZ_SERVER_PORT: "8080"

# --- blocco base per tutti i zone hub ---
x-zone-hub-base: &zone-hub-base
  image: fmasci/sc-edge-hub:latest
  build:
    context: ../..
    dockerfile: deploy/docker/edge-hub.Dockerfile
  restart: unless-stopped
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8080/healthz" ]
    interval: 60s
    timeout: 30s
    retries: 10
  networks:
    - zone-hub-bridge
  depends_on:
    zone-hub-redis-cache:
      condition: service_healthy

services:

  # --- REDIS CACHE ---
  zone-hub-redis-cache:
    image: redis:latest
    container_name: zone-hub-${EDGE_ZONE}-cache
    hostname: zone-hub-${EDGE_ZONE}-cache
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - zone-hub-bridge

  # --- FILTER ---
  zone-hub-filter-01:
    <<: *zone-hub-base
    container_name: zone-hub-filter-${EDGE_ZONE}-01
    environment:
      <<: *zone-hub-env
      HUB_ID: "zone-hub-filter-01"
      SERVICE_MODE: "edge_hub_filter"

  zone-hub-filter-02:
    <<: *zone-hub-base
    container_name: zone-hub-filter-${EDGE_ZONE}-02
    environment:
      <<: *zone-hub-env
      HUB_ID: "zone-hub-filter-02"
      SERVICE_MODE: "edge_hub_filter"

  # --- CLEANER ---
  zone-hub-cleaner-01:
    <<: *zone-hub-base
    container_name: zone-hub-cleaner-${EDGE_ZONE}-01
    environment:
      <<: *zone-hub-env
      HUB_ID: "zone-hub-cleaner-01"
      SERVICE_MODE: "edge_hub_cleaner"

  # --- AGGREGATOR ---
  zone-hub-aggregator-01:
    <<: *zone-hub-base
    container_name: zone-hub-aggregator-${EDGE_ZONE}-01
    environment:
      <<: *zone-hub-env
      HUB_ID: "zone-hub-aggregator-01"
      SERVICE_MODE: "edge_hub_aggregator"

  zone-hub-aggregator-02:
    <<: *zone-hub-base
    container_name: zone-hub-aggregator-${EDGE_ZONE}-02
    environment:
      <<: *zone-hub-env
      HUB_ID: "zone-hub-aggregator-02"
      SERVICE_MODE: "edge_hub_aggregator"

  # --- CONFIGURATOR ---
  zone-hub-configurator-01:
    <<: *zone-hub-base
    container_name: zone-hub-configurator-${EDGE_ZONE}-01
    environment:
      <<: *zone-hub-env
      HUB_ID: "zone-hub-configurator-01"
      SERVICE_MODE: "edge_hub_configuration"

  zone-hub-configurator-02:
    <<: *zone-hub-base
    container_name: zone-hub-configurator-${EDGE_ZONE}-02
    environment:
      <<: *zone-hub-env
      HUB_ID: "zone-hub-configurator-02"
      SERVICE_MODE: "edge_hub_configuration"

networks:
  zone-hub-bridge:
    name: zone-hub-${EDGE_ZONE}-bridge
    driver: bridge
