services:

  region-hub-01:
    image: intermediate-fog-hub:latest
    build:
      context: ../..
      dockerfile: deploy/docker/intermediate-fog-hub.Dockerfile
    container_name: region-hub-${REGION}-01
    environment:
      - HUB_ID=region-hub-01
      - KAFKA_BROKER_ADDRESS=${REGION}.kafka-broker.local
      - KAFKA_BROKER_PORT=${KAFKA_PORT}
      - POSTGRES_CLOUD_HOST=metadata-db.cloud.sensorcontinuum.node
      - POSTGRES_CLOUD_PORT=${POSTGRES_CLOUD_PORT}
      - POSTGRES_REGION_HOST=metadata-db.${REGION}.sensorcontinuum.node
      - POSTGRES_REGION_PORT=${POSTGRES_REGION_PORT}
      - POSTGRES_SENSOR_HOST=mesurament-db.${REGION}.sensorcontinuum.node
      - POSTGRES_SENSOR_PORT=${POSTGRES_SENSOR_PORT}
      - HEALTHZ_SERVER=true
      - HEALTHZ_SERVER_PORT=8080
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthz" ]
      interval: 60s
      timeout: 30s
      retries: 10
    networks:
      - region-hub-bridge

networks:
  region-hub-bridge:
    name: region-hub-${REGION}-bridge
    driver: bridge