services:

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb-compose
    hostname: timescaledb-host
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: sensorcontinuum
    ports:
      - "5432:5432"
    volumes:
      - ../../configs/postgresql/init-region-sensors-db.sql:/docker-entrypoint-initdb.d/init-region-sensors-db.sql:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "sensorcontinuum" ]
      interval: 10s
      timeout: 5s
      retries: 3

  cloud_metadatadb:
    image: postgis/postgis:latest
    container_name: metadatadb-cloud-compose
    hostname: metadatadb-cloud-host
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: sensorcontinuum
    ports:
      - "5433:5432"
    volumes:
      - ../../configs/postgresql/init-cloud-metadata-db.sql:/docker-entrypoint-initdb.d/init-postgis.sql:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "sensorcontinuum" ]
      interval: 10s
      timeout: 5s
      retries: 3

  region_metadatadb:
    image: postgis/postgis:latest
    container_name: metadatadb-region-compose
    hostname: metadatadb-region-host
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: sensorcontinuum
    ports:
      - "5434:5432"
    volumes:
      - ../../configs/postgresql/init-region-metadata-db.sql:/docker-entrypoint-initdb.d/init-postgis.sql:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "sensorcontinuum" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis-compose
    hostname: redis-storage
    command: ["--bind", "0.0.0.0", "--protected-mode", "no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-compose
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: [ "CMD", "zkServer.sh", "status" ]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-compose
    hostname: kafka-broker
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka-broker:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-broker:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server kafka:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
        zookeeper:
          condition: service_healthy

  mosquitto:
    build:
      context: ../..
      dockerfile: deploy/docker/mosquitto-local.Dockerfile
    container_name: mosquitto-compose
    hostname: mosquitto-broker
    ports:
      - "1883:1883"
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h localhost -t '$$SYS/broker/version' -C 1 -W 2 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  intermediate-fog-hub:
    build:
      context: ../..
      dockerfile: deploy/docker/intermediate-fog-hub.Dockerfile
    container_name: intermediate-fog-hub-compose
    environment:
      - REGION_ID=1
      - REGION_NAME=region-001
      - EDGE_MACROZONE=build-0001
      - HUB_ID=region-hub-001
      - KAFKA_BROKER_ADDRESS=kafka-broker
      - KAFKA_BROKER_PORT=9094
      - POSTGRES_CLOUD_HOST=metadatadb-cloud-host
      - POSTGRES_CLOUD_PORT=5432
      - POSTGRES_REGION_HOST=metadatadb-region-host
      - POSTGRES_REGION_PORT=5432
      - POSTGRES_SENSOR_HOST=timescaledb-host
      - POSTGRES_SENSOR_PORT=5432
      - LOG_LEVEL=debug
    depends_on:
      kafka:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
      cloud_metadatadb:
        condition: service_healthy
      region_metadatadb:
        condition: service_healthy
    restart: unless-stopped

  proximity-fog-hub:
    build:
      context: ../..
      dockerfile: deploy/docker/proximity-fog-hub.Dockerfile
    container_name: proximity-fog-hub-compose
    environment:
      - REGION=region-001
      - EDGE_MACROZONE=build-0001
      - HUB_ID=proximity-hub-001
      - KAFKA_BROKER_ADDRESS=kafka-broker
      - KAFKA_BROKER_PORT=9094
      - MQTT_BROKER_ADDRESS=mosquitto-broker
      - POSTGRES_HOST=timescaledb-host
      - POSTGRES_PORT=5432
      - LOG_LEVEL=debug
    depends_on:
      mosquitto:
        condition: service_healthy
      kafka:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
    restart: unless-stopped

  edge-hub:
    build:
      context: ../..
      dockerfile: deploy/docker/edge-hub.Dockerfile
    container_name: edge-hub-compose
    environment:
      - EDGE_MACROZONE=build-0001
      - EDGE_ZONE=floor-001
      - HUB_ID=zone-hub-001
      - MQTT_BROKER_ADDRESS=mosquitto-broker
      - REDIS_ADDRESS=redis-storage
      - LOG_LEVEL=debug
    depends_on:
      mosquitto:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  sensor-agent-1:
    build:
      context: ../..
      dockerfile: deploy/docker/sensor-agent.Dockerfile
    container_name: sensor-agent-1-compose
    environment:
      - EDGE_MACROZONE=build-0001
      - EDGE_ZONE=floor-001
      - SENSOR_ID=sensor-001
      - MQTT_BROKER_ADDRESS=mosquitto-broker
      - HEALTHZ_SERVER=true
      - HEALTHZ_SERVER_PORT=8080
    depends_on:
      mosquitto:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthz" ]
      interval: 60s
      timeout: 30s
      retries: 10

  sensor-agent-2:
    build:
      context: ../..
      dockerfile: deploy/docker/sensor-agent.Dockerfile
    container_name: sensor-agent-2-compose
    environment:
      - EDGE_MACROZONE=build-0001
      - EDGE_ZONE=floor-001
      - SENSOR_ID=sensor-002
      - MQTT_BROKER_ADDRESS=mosquitto-broker
      - HEALTHZ_SERVER=true
      - HEALTHZ_SERVER_PORT=8080
    depends_on:
      mosquitto:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthz" ]
      interval: 60s
      timeout: 30s
      retries: 10

networks:
  default:
    driver: bridge
    name: sensorcontinuum-local-network