services:

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - iot-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka-broker
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka-broker:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    command: >
      bash -c "
        /opt/bitnami/scripts/kafka/run.sh &
        sleep 20 &&
        kafka-topics.sh --delete --topic raw-data-edge-hub_build-0001 --bootstrap-server kafka-broker:9094
        kafka-topics.sh --create --topic raw-data-edge-hub_build-0001 --partitions 5 --replication-factor 1 --bootstrap-server kafka-broker:9094
        wait
      "
    networks:
      - iot-net

  mosquitto:
    build:
      context: ../..
      dockerfile: deploy/docker/mosquitto-local.Dockerfile
    container_name: mosquitto-compose
    hostname: mosquitto-broker
    ports:
      - "1883:1883"
    networks:
      - iot-net

    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h localhost -t '$$SYS/broker/version' -C 1 -W 2 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  intermediate-fog-hub:
    build:
      context: ../..
      dockerfile: deploy/docker/intermediate-fog-hub.Dockerfile
    container_name: intermediate-fog-hub-compose
    environment:
      - BUILDING_ID=building-0001
      - HUB_ID=intermediate-hub-001
      - KAFKA_BROKER_ADDRESS=kafka-broker
      - KAFKA_BROKER_PORT=9094
      # - EDGE_HUB_TOPIC=raw-data-edge-hub_build-0001
      # - EDGE_HUB_TOPIC_PARTITION=1
    hostname: intermediate-fog-hub
    depends_on:
      - kafka
    networks:
      - iot-net

  proximity-fog-hub:
    build:
      context: ../..
      dockerfile: deploy/docker/proximity-fog-hub.Dockerfile
    container_name: proximity-fog-hub-compose
    environment:
      - BUILDING_ID=building-0001
      - HUB_ID=proximity-hub-001
      - KAFKA_BROKER_ADDRESS=kafka-broker
      - KAFKA_BROKER_PORT=9094
      # - EDGE_HUB_TOPIC=raw-data-edge-hub_build-0001
      # - EDGE_HUB_TOPIC_PARTITION=0
    hostname: proximity-fog-hub
    depends_on:
      - kafka
    networks:
      - iot-net

  edge-hub:
    build:
      context: ../..
      dockerfile: deploy/docker/edge-hub.Dockerfile
    container_name: edge-hub-compose
    environment:
      - BUILDING_ID=building-0001
      - FLOOR_ID=floor-001
      - HUB_ID=hub-001
      - MQTT_BROKER_ADDRESS=mosquitto-broker
      - KAFKA_BROKER_ADDRESS=kafka-broker
      - KAFKA_BROKER_PORT=9094
    hostname: edge-hub
    depends_on:
      mosquitto:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/healthy || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - iot-net

  sensor-agent-1:
    build:
      context: ../..
      dockerfile: deploy/docker/sensor-agent.Dockerfile
    container_name: sensor-agent-1-compose
    environment:
      - BUILDING_ID=building-0001
      - FLOOR_ID=floor-001
      - SENSOR_ID=sensor-0001
      - MQTT_BROKER_ADDRESS=mosquitto-broker
    depends_on:
      edge-hub:
        condition: service_healthy
    networks:
      - iot-net

  sensor-agent-2:
    build:
      context: ../..
      dockerfile: deploy/docker/sensor-agent.Dockerfile
    container_name: sensor-agent-2-compose
    environment:
      - BUILDING_ID=building-0001
      - FLOOR_ID=floor-001
      - SENSOR_ID=sensor-0002
      - MQTT_BROKER_ADDRESS=mosquitto-broker
    depends_on:
      - edge-hub
    networks:
      - iot-net

networks:
  iot-net:
    driver: bridge