services:

  pumba:
    image: gaiaadm/pumba
    container_name: pumba
    command: >
      netem
      --duration 10m
      delay
      --time 300
      --jitter 50
      --correlation 20
      loss
      --percent 5
      re2:.macrozone-hub-build-0001-01
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_ADMIN
    networks:
      # Lista tutte le reti dove ci sono container target
      - zone-hub-floor-001-bridge
      - macrozone-hub-build-0001-bridge
      - region-hub-region-001-bridge

networks:
  # Dichiarazione delle reti esterne
  zone-hub-floor-001-bridge:
    external: true
  macrozone-hub-build-0001-bridge:
    external: true
  region-hub-region-001-bridge:
    external: true