services:

  macrozone-hub-postgres-cache:
    image: timescale/timescaledb:latest-pg17
    container_name: macrozone-hub-${EDGE_MACROZONE}-cache
    hostname: macrozone-hub-${EDGE_MACROZONE}-cache
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: sensorcontinuum
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ../../configs/postgresql/init-proximity-cache.sql:/docker-entrypoint-initdb.d/init-region-sensors-db.sql:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "sensorcontinuum" ]
      interval: 60s
      timeout: 10s
      retries: 10
    networks:
      - macrozone-hub-bridge

  macrozone-hub-01:
    image: fmasci/proximity-fog-hub:latest
    build:
      context: ../..
      dockerfile: deploy/docker/proximity-fog-hub.Dockerfile
    container_name: macrozone-hub-${EDGE_MACROZONE}-01
    environment:
      - EDGE_MACROZONE=${EDGE_MACROZONE}
      - HUB_ID=macrozone-hub-01
      - KAFKA_BROKER_ADDRESS=${REGION}.kafka-broker.local
      - KAFKA_BROKER_PORT=9094
      - MQTT_BROKER_ADDRESS=${EDGE_MACROZONE}.mqtt-broker.local
      - POSTGRES_HOST=macrozone-hub-${EDGE_MACROZONE}-cache
      - POSTGRES_PORT=5432
      - HEALTHZ_SERVER=true
      - HEALTHZ_SERVER_PORT=8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthz" ]
      interval: 60s
      timeout: 30s
      retries: 10
    depends_on:
      macrozone-hub-postgres-cache:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - macrozone-hub-bridge

networks:
  macrozone-hub-bridge:
    name: macrozone-hub-${EDGE_MACROZONE}-bridge
    driver: bridge